### PR TITLE
compatibility fixes for recent changes in FACT_core

### PR DESCRIPTION
**Pull request by jstucke**
- updated config handling in the plugin to be compatible with [#867](https://github.com/fkie-cad/FACT_core/pull/867)
- used test fixture to be compatible with [#786](https://github.com/fkie-cad/FACT_core/pull/786)

### CODE REVIEW

**Comment by maringuu** [comment]
Code LGTM. I don't like the commit message personally.
I'd like to include a commit hash in it too and also the changes addressed in this PR originate from two different FACT PRs.

If FACT is a bit more stable in the future we could maybe let plugins specify for which fact version they are programmed.

**Comment by jstucke** [comment]
> If FACT is a bit more stable in the future we could maybe let plugins specify for which fact version they are programmed.

Actually FACT was pretty stable regarding support with external plugins. Ideally, we don't break compatibility with external plugins (like [#867](https://github.com/fkie-cad/FACT_core/pull/867) and [#786](https://github.com/fkie-cad/FACT_core/pull/786) did). The migration to PostgreSQL also did. We also don't know if some people implemented custom plugins that we broke. Maybe we should add a document somewhere (in the github wiki probably) that describes what needs to be changed to get custom plugins to work again.

**Comment by jstucke** [comment]
I updated the commit message and the PR description

**Comment by maringuu** [comment]
LGTM!

**Pull request merged**
